# Generated by Django 3.1.7 on 2021-05-27 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='grade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
