# Generated by Django 3.1.7 on 2021-02-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='label',
        ),
        migrations.AddField(
            model_name='problem',
            name='label',
            field=models.ManyToManyField(to='problems.Label'),
        ),
    ]
