# Generated by Django 3.1.7 on 2021-02-26 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20210226_0001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='label',
            new_name='labels',
        ),
    ]
