# Generated by Django 3.1.7 on 2021-05-28 15:45

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problem_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='themes',
            field=models.ManyToManyField(blank=True, null=True, to='problems.Theme'),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='color',
            field=colorfield.fields.ColorField(choices=[('#555B6E', 'Independence'), ('#89B0AE', 'Morning Blue'), ('#BEE3DB', 'Powder Blue'), ('#FAF9F9', 'Cultured'), ('#FFD6BA', 'Apricot')], default='#555B6E', max_length=18),
        ),
        migrations.AlterField(
            model_name='problem',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, to='problems.Attribute'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='parents',
            field=models.ManyToManyField(blank=True, null=True, related_name='_problem_parents_+', to='problems.Problem'),
        ),
    ]
