# Generated by Django 3.1.7 on 2021-08-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0009_auto_20210717_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='name',
            field=models.CharField(blank=True, help_text='e.g. butterfly theorem', max_length=255),
        ),
        migrations.AlterField(
            model_name='problem',
            name='number',
            field=models.IntegerField(blank=True, help_text='Number, under which the problem was proposed', null=True),
        ),
    ]
