# Generated by Django 3.1.7 on 2021-08-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0010_auto_20210829_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['-id']},
        ),
    ]
